image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:


  - docker-compose up --build --no-recreate -d

  - sleep 1m
  - java "-Dspring.datasource.url=jdbc:mysql://localhost:3306/app" -jar artifacts/aqa-shop.jar
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true
